//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ms_icon_H
#define METASPRITE_ms_icon_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ms_icon_TILE_ORIGIN 0
#define ms_icon_TILE_W 8
#define ms_icon_TILE_H 16
#define ms_icon_WIDTH 1024
#define ms_icon_HEIGHT 1024
#define ms_icon_TILE_COUNT 6952
#define ms_icon_PALETTE_COUNT 8
#define ms_icon_COLORS_PER_PALETTE 4
#define ms_icon_TOTAL_COLORS 32
#define ms_icon_PIVOT_X 512
#define ms_icon_PIVOT_Y 512
#define ms_icon_PIVOT_W 1024
#define ms_icon_PIVOT_H 1024

BANKREF_EXTERN(ms_icon)

extern const palette_color_t ms_icon_palettes[32];
extern const uint8_t ms_icon_tiles[111232];

extern const metasprite_t* const ms_icon_metasprites[1];

#endif
