#!/usr/bin/env python3
"""Compile assets/system_font.txt into the C glyph table used by src/text.c."""

from __future__ import annotations

import argparse
import pathlib

FIRST = 32
LAST = 126
ROWS = 7
MAX_WIDTH = 5


def parse(path: pathlib.Path) -> dict[int, list[str]]:
    glyphs: dict[int, list[str]] = {}
    current: int | None = None
    rows: list[str] = []

    def finish() -> None:
        if current is None:
            return
        if len(rows) != ROWS:
            raise SystemExit(f"glyph {chr(current)!r}: expected {ROWS} rows, got {len(rows)}")
        widths = {len(row) for row in rows}
        if len(widths) != 1:
            raise SystemExit(f"glyph {chr(current)!r}: rows have different widths {sorted(widths)}")
        width = widths.pop()
        if not 1 <= width <= MAX_WIDTH:
            raise SystemExit(f"glyph {chr(current)!r}: width {width} outside 1-{MAX_WIDTH}")
        if any(set(row) - {"#", "."} for row in rows):
            raise SystemExit(f"glyph {chr(current)!r}: rows may contain only '#' and '.'")
        if current in glyphs:
            raise SystemExit(f"glyph {chr(current)!r} defined twice")
        glyphs[current] = list(rows)

    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.rstrip()
        if line.startswith("glyph "):
            finish()
            name = line[len("glyph "):]
            if name == "space":
                current = ord(" ")
            elif len(name) == 1:
                current = ord(name)
            else:
                raise SystemExit(f"line {number}: bad glyph name {name!r}")
            if not FIRST <= current <= LAST:
                raise SystemExit(f"line {number}: glyph {name!r} outside printable ASCII")
            rows = []
        elif current is not None and line and not line.startswith("#"):
            rows.append(line)
        elif current is not None and line.startswith("#") and set(line) <= {"#", "."}:
            rows.append(line)
    finish()

    missing = [chr(code) for code in range(FIRST, LAST + 1) if code not in glyphs]
    if missing:
        raise SystemExit(f"missing glyphs: {''.join(missing)!r}")
    return glyphs


def render(glyphs: dict[int, list[str]], source: pathlib.Path) -> str:
    lines = [
        f"/* Generated by tools/fontgen.py from {source.as_posix()}. Do not edit. */",
        "#include \"text.h\"",
        "",
        f"const UINT8 text_font_width[{LAST - FIRST + 1}] = {{",
    ]
    codes = range(FIRST, LAST + 1)
    widths = [str(len(glyphs[code][0])) for code in codes]
    for start in range(0, len(widths), 16):
        lines.append("    " + ", ".join(widths[start:start + 16]) + ",")
    lines += ["};", "", f"const UINT8 text_font_rows[{LAST - FIRST + 1}][{ROWS}] = {{"]
    for code in codes:
        values = []
        for row in glyphs[code]:
            value = 0
            for column, pixel in enumerate(row):
                if pixel == "#":
                    value |= 0x80 >> column
            values.append(f"0x{value:02x}u")
        label = "space" if code == 32 else chr(code).replace("\\", "backslash")
        lines.append(f"    {{{', '.join(values)}}}, /* {label} */")
    lines += ["};", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    args = parser.parse_args()

    text = render(parse(args.source), args.source)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != text:
            raise SystemExit(f"{args.output} is stale; run `make font`")
        return
    args.output.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
